/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Expense {
  'id' : bigint,
  'expenseType' : string,
  'submitterName' : string,
  'date' : Time,
  'createdAt' : Time,
  'updatedAt' : Time,
  'amount' : bigint,
}
export type ExpenseId = bigint;
export interface ExpenseInput {
  'expenseType' : string,
  'submitterName' : string,
  'date' : Time,
  'amount' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createExpense' : ActorMethod<[ExpenseInput], Expense>,
  'deleteExpense' : ActorMethod<[ExpenseId], undefined>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  /**
   * / Returns the total expense amount from the earliest recorded expense year up to the current year.
   */
  'getAllYearsTotalToNow' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyTotal' : ActorMethod<[Time], bigint>,
  /**
   * / Returns the total expense amount for the current month up to now.
   */
  'getMonthlyTotalToNow' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Returns the total expense amount for the current year up to now.
   */
  'getYearlyTotalToNow' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateExpense' : ActorMethod<[ExpenseId, ExpenseInput], Expense>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];