/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExpenseInput = IDL.Record({
  'expenseType' : IDL.Text,
  'submitterName' : IDL.Text,
  'date' : Time,
  'amount' : IDL.Nat,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'expenseType' : IDL.Text,
  'submitterName' : IDL.Text,
  'date' : Time,
  'createdAt' : Time,
  'updatedAt' : Time,
  'amount' : IDL.Nat,
});
export const ExpenseId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createExpense' : IDL.Func([ExpenseInput], [Expense], []),
  'deleteExpense' : IDL.Func([ExpenseId], [], []),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllYearsTotalToNow' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyTotal' : IDL.Func([Time], [IDL.Nat], ['query']),
  'getMonthlyTotalToNow' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getYearlyTotalToNow' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateExpense' : IDL.Func([ExpenseId, ExpenseInput], [Expense], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExpenseInput = IDL.Record({
    'expenseType' : IDL.Text,
    'submitterName' : IDL.Text,
    'date' : Time,
    'amount' : IDL.Nat,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'expenseType' : IDL.Text,
    'submitterName' : IDL.Text,
    'date' : Time,
    'createdAt' : Time,
    'updatedAt' : Time,
    'amount' : IDL.Nat,
  });
  const ExpenseId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createExpense' : IDL.Func([ExpenseInput], [Expense], []),
    'deleteExpense' : IDL.Func([ExpenseId], [], []),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllYearsTotalToNow' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyTotal' : IDL.Func([Time], [IDL.Nat], ['query']),
    'getMonthlyTotalToNow' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getYearlyTotalToNow' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateExpense' : IDL.Func([ExpenseId, ExpenseInput], [Expense], []),
  });
};

export const init = ({ IDL }) => { return []; };